### ISSUE TITLE
Enable cors with all headers allowed in f2f lambda

### ISSUE THREAD

**Issue by gmuditdce** [filetrust/cdr-plugin-folder-to-folder#536]
Enable cors will all headers in f2f lambda
We need more headers to integrate with javascript
The current allowed headers does no suffice

**Comment by gmuditdce** [comment]
Done with this PR on lambdas repo - https://github.com/filetrust/cdr-plugin-folder-to-folder-aws-lambdas/pull/3

**Comment by MaNe2020** [comment]
@gmuditdce I still get this 

"Access to fetch at 'http://localhost:8000/pre-processor/pre-process' from origin 'http://localhost:8004' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

Is this connected to the issue. 

And due to this I have 
![image](https://user-images.githubusercontent.com/70108899/123401963-8f939280-d5a7-11eb-8c38-cdf3ac258064.png)

**Comment by chrisdiao** [comment]
@MaNe2020 could you please check if this is still happing once you have done the workaround that @rajmbcoderx provided?
`To use "Clear Data" before "Load Files"`

**Comment by chrisdiao** [comment]
This has been included in v0.13.0 release
